# Numpy Exercise 1

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
A = {'Skill':[1,4,0,9],'Running':[8,7,1,1],'Smoking':[4,0,2,1],'Books':[2,4,3,0]}

In [7]:
A

{'Skill': [1, 4, 0, 9],
 'Running': [8, 7, 1, 1],
 'Smoking': [4, 0, 2, 1],
 'Books': [2, 4, 3, 0]}

In [8]:
B = pd.DataFrame(A)

In [9]:
B

   Skill  Running  Smoking  Books
0      1        8        4      2
1      4        7        0      4
2      0        1        2      3
3      9        1        1      0

In [10]:
C = pd.DataFrame(A,['Q1','Q2','Q3','Q4'])

In [11]:
C

    Skill  Running  Smoking  Books
Q1      1        8        4      2
Q2      4        7        0      4
Q3      0        1        2      3
Q4      9        1        1      0

In [12]:
data = {'Days':['Mon','Tue','Wed'],'Hours_Coded':[4,7,14]}

In [13]:
df = pd.DataFrame(data)

In [14]:
df

  Days  Hours_Coded
0  Mon            4
1  Tue            7
2  Wed           14

In [15]:
data1 = {'Hours_Coded':[4,7,14]}
df1 = pd.DataFrame(data1,['Mon','Tue','Wed'])

In [16]:
df1

     Hours_Coded
Mon            4
Tue            7
Wed           14

In [17]:
# Calcultate my intensity

df_intensity = df['Hours_Coded']/24

In [18]:
df_intensity

0    0.166667
1    0.291667
2    0.583333
Name: Hours_Coded, dtype: float64

In [19]:
# Calcultate my intensity

df_intensity1 = df1['Hours_Coded']/24
df_intensity1

Mon    0.166667
Tue    0.291667
Wed    0.583333
Name: Hours_Coded, dtype: float64

# Numpy

In [20]:
trades = np.array([-100,250,-50,400,-150])

In [21]:
print(f'Average: {np.mean(trades)}')

Average: 70.0

In [22]:
print(f'Volatility: {np.std(trades)}')

Volatility: 215.87033144922904

Exercise 1.1 - Create a Matrix: Generate a 10 \times 3 NumPy array of random floats representing price changes for 3 different assets over 10 days.

In [23]:
price = np.round(np.random.rand(10,3),2)
price

array([[0.63, 0.87, 0.79],
       [0.94, 0.78, 0.93],
       [0.66, 0.25, 0.75],
       [0.97, 0.46, 0.94],
       [0.55, 0.  , 0.97],
       [0.44, 0.57, 0.19],
       [0.05, 0.94, 0.74],
       [0.72, 0.07, 0.99],
       [0.05, 0.92, 0.23],
       [0.27, 0.42, 0.54]])

Exercise 1.2 - Normalization: Subtract the mean of each column from itself (centering the data).

In [24]:
# mean for each column 

column1 = price[:,0] 
mean_column1 = np.mean(column1)
print(f'The Mean of column1: {mean_column1}')

column2 = price[:,1]
mean_column2 = np.mean(column2)
print(f'The Mean of column2: {mean_column2}')

column3 = price[:,2]
mean_column3 = np.mean(column3)
print(f'The Mean of column3: {mean_column3}')

The Mean of column1: 0.5279999999999999
The Mean of column2: 0.528
The Mean of column3: 0.7070000000000001

In [25]:
# Subtracting the mean of each column from itself 

price_change1 = column1 - mean_column1
print(f'The price change for column1: {price_change1}')

price_change2 = column2 - mean_column2
print(f'The price change for column2: {price_change2}')

price_change3 = column3 - mean_column3
print(f'The price change for column3: {price_change3}')

The price change for column1: [ 0.102  0.412  0.132  0.442  0.022 -0.088 -0.478  0.192 -0.478 -0.258]
The price change for column2: [ 0.342  0.252 -0.278 -0.068 -0.528  0.042  0.412 -0.458  0.392 -0.108]
The price change for column3: [ 0.083  0.223  0.043  0.233  0.263 -0.517  0.033  0.283 -0.477 -0.167]

In [26]:
# how to arrange it back to a 10,3

prices1 = np.array(price_change1)
prices2 = np.array(price_change2)
prices3 = np.array(price_change3)

new_price = np.array([[prices1],[prices2],[prices3]])
new_price

array([[[ 0.102,  0.412,  0.132,  0.442,  0.022, -0.088, -0.478,  0.192,
         -0.478, -0.258]],

       [[ 0.342,  0.252, -0.278, -0.068, -0.528,  0.042,  0.412, -0.458,
          0.392, -0.108]],

       [[ 0.083,  0.223,  0.043,  0.233,  0.263, -0.517,  0.033,  0.283,
         -0.477, -0.167]]])

Exercise 1.3 - Risk Calc: Calculate the Standard Deviation for each asset (column) to see which is the most volatile.

In [27]:
# Standard Deviation for each asset(column)

sd_column1 = np.std(column1)
print(f'The Standard Deviation for column1: {sd_column1}')

sd_column2 = np.std(column2)
print(f'The Standard Deviation for column2: {sd_column2}')

sd_column3 = np.std(column3)
print(f'The Standard Deviation for column3: {sd_column3}')

max_sd = [sd_column1,sd_column2,sd_column3]
print(f'The most volatile: {np.max(max_sd)}')

The Standard Deviation for column1: 0.31009030942614124
The Standard Deviation for column2: 0.32981206769916716
The Standard Deviation for column3: 0.28032302795168296
The most volatile: 0.32981206769916716

Exercise 1.4 - The "Crash" Scenario: Use a Boolean mask to find any days where price changes were more than 2 standard deviations from the mean.

In [28]:
price

array([[0.63, 0.87, 0.79],
       [0.94, 0.78, 0.93],
       [0.66, 0.25, 0.75],
       [0.97, 0.46, 0.94],
       [0.55, 0.  , 0.97],
       [0.44, 0.57, 0.19],
       [0.05, 0.94, 0.74],
       [0.72, 0.07, 0.99],
       [0.05, 0.92, 0.23],
       [0.27, 0.42, 0.54]])

In [29]:
# (axis=0) column

price.sum(axis=0)

array([5.28, 5.28, 7.07])

In [30]:
# (axis=1) row

price.sum(axis=1)

array([2.29, 2.65, 1.66, 2.37, 1.52, 1.2 , 1.73, 1.78, 1.2 , 1.23])

In [31]:
prices = price - price.sum(axis=0)
prices

array([[-4.65, -4.41, -6.28],
       [-4.34, -4.5 , -6.14],
       [-4.62, -5.03, -6.32],
       [-4.31, -4.82, -6.13],
       [-4.73, -5.28, -6.1 ],
       [-4.84, -4.71, -6.88],
       [-5.23, -4.34, -6.33],
       [-4.56, -5.21, -6.08],
       [-5.23, -4.36, -6.84],
       [-5.01, -4.86, -6.53]])

In [33]:
stds = price.std(axis=0)
stds

array([0.31009031, 0.32981207, 0.28032303])